'use client';
import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
export default function SourceWindow({component,onClose}){
 const panel=useRef(null),drag=useRef(null),resizing=useRef(null);
 const [dimensions,setDimensions]=useState(null),[position,setPosition]=useState(null),[source,setSource]=useState(null),[error,setError]=useState('');
 useEffect(()=>{setSource(null);setError('');const controller=new AbortController();fetch(`/api/source?snapshotId=${encodeURIComponent(component.snapshotId)}&fileId=${encodeURIComponent(component.fileIds[0])}`,{signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setSource(body);}).catch(reason=>{if(reason.name!=='AbortError')setError(reason.message);});return()=>controller.abort();},[component]);
 useEffect(()=>{const previous=document.activeElement;panel.current?.focus();return()=>{if(previous?.isConnected)previous.focus();};},[]);
 const start=event=>{if(event.button!==0||event.target.closest('button'))return;const rect=panel.current.getBoundingClientRect();drag.current={x:event.clientX-rect.left,y:event.clientY-rect.top};event.currentTarget.setPointerCapture(event.pointerId);};
 const move=event=>{if(!drag.current)return;const rect=panel.current.getBoundingClientRect();setPosition({left:Math.max(0,Math.min(window.innerWidth-rect.width,event.clientX-drag.current.x)),top:Math.max(0,Math.min(window.innerHeight-60,event.clientY-drag.current.y))});};
 return <section ref={panel} role="dialog" aria-modal="false" aria-label="Source viewer" tabIndex={-1} className="source-window" style={{...position,...dimensions}} onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();onClose();}}}>
 <header className="reader-header" onPointerDown={start} onPointerMove={move} onPointerUp={()=>{drag.current=null;}} onLostPointerCapture={()=>{drag.current=null;}}><div><span className="eyebrow">COMMIT-PINNED SOURCE · DRAG TO MOVE</span><h2>{source?.path||'Loading source…'}</h2></div><button className="icon-button" aria-label="Close source" onClick={onClose}><X size={20}/></button></header>
 {error?<p role="alert" className="reader-error">{error}</p>:source?<div className="code-scroll" tabIndex={0}><ol start={source.startLine}>{source.lines.map((line,index)=><li key={index}><code>{line||' '}</code></li>)}</ol></div>:<div className="reader-loading">Reading the selected source…</div>}
 <button className="source-resize" aria-label="Resize source window" title="Drag to resize; arrow keys adjust size" onPointerDown={event=>{const rect=panel.current.getBoundingClientRect();resizing.current={x:event.clientX,y:event.clientY,width:rect.width,height:rect.height,left:rect.left,top:rect.top};event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{const r=resizing.current;if(r)setDimensions({width:Math.max(280,Math.min(window.innerWidth-r.left-8,r.width+event.clientX-r.x)),height:Math.max(200,Math.min(window.innerHeight-r.top-8,r.height+event.clientY-r.y))});}} onPointerUp={()=>{resizing.current=null;}} onLostPointerCapture={()=>{resizing.current=null;}} onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const r=panel.current.getBoundingClientRect();setDimensions({width:Math.max(280,Math.min(window.innerWidth-r.left-8,r.width+(event.key==='ArrowRight'?20:event.key==='ArrowLeft'?-20:0))),height:Math.max(200,Math.min(window.innerHeight-r.top-8,r.height+(event.key==='ArrowDown'?20:event.key==='ArrowUp'?-20:0)))});}}>◢</button>
 </section>;
}
