import {z} from 'zod';

const short=z.string().trim().min(1).max(4096);
export const repositoryInput=z.string().trim().url().max(500);
export const citationSchema=z.object({id:z.string().uuid().optional(),fileId:z.string().uuid(),path:z.string().min(1).max(500),startLine:z.number().int().positive(),endLine:z.number().int().positive(),chunkId:z.string().uuid().optional()}).strict().refine(value=>value.endLine>=value.startLine,{message:'Citation end line precedes start line.'});
export const claimSchema=z.object({text:short,citationIds:z.array(z.string().uuid()).min(1).max(5)}).strict();
export const answerSchema=z.object({status:z.enum(['answered','partial','insufficient_evidence']),summary:short,maxClaims:z.undefined().optional(),claims:z.array(claimSchema).max(20),limitations:z.array(z.string().trim().min(1).max(500)).max(8),followUps:z.array(z.string().trim().min(1).max(240)).max(5),citations:z.array(citationSchema).max(20)}).strict();
export const modelAnswerSchema=z.object({status:z.enum(['answered','partial','insufficient_evidence']),summary:short,claims:z.array(z.object({text:short,citationFileIds:z.array(z.string().uuid()).max(5)}).strict()).max(20),limitations:z.array(z.string().trim().min(1).max(500)).max(8),followUps:z.array(z.string().trim().min(1).max(240)).max(5),citations:z.array(z.object({fileId:z.string().uuid(),path:z.string().min(1).max(500),startLine:z.number().int().positive(),endLine:z.number().int().positive()}).strict()).max(20)}).strict();
export const reportNodeSchema=z.object({id:z.string().min(1),name:short,kind:short,group:z.string().min(1).optional(),icon:z.enum(['terminal','database','server','network','code','layers']),accent:z.enum(['mint','violet','amber','cyan','rose','blue']),summary:z.string().trim().min(1),role:z.string().trim().min(1),tags:z.array(z.string().trim().min(1)),fileIds:z.array(z.string()).min(1),citationIds:z.array(z.string().uuid())});
export const reportSchema=z.object({summary:short,stack:z.array(z.object({name:short,evidence:z.array(z.string().uuid()).min(1)})),profile:z.enum(['signal','violet','ember']),components:z.array(reportNodeSchema).min(1),edges:z.array(z.object({source:z.string(),target:z.string(),label:z.string(),inferred:z.boolean()})),workflows:z.array(z.object({name:short,steps:z.array(z.object({componentId:z.string(),label:short,citationIds:z.array(z.string().uuid())})).min(1)})),limitations:z.preprocess(value=>typeof value==='string'?[value]:value??[],z.array(z.string()))});
export const modelReportSchema=z.object({summary:short,profile:z.enum(['signal','violet','ember']),components:z.array(z.object({id:z.string().min(1),name:short,kind:short,group:z.string().min(1).optional(),icon:z.enum(['terminal','database','server','network','code','layers']),accent:z.enum(['mint','violet','amber','cyan','rose','blue']),summary:z.string().trim().min(1),role:z.string().trim().min(1),tags:z.array(z.string().trim().min(1)),fileIds:z.array(z.string()).min(1)})).min(1),edges:z.array(z.object({source:z.string(),target:z.string(),label:z.string(),inferred:z.boolean()})),workflows:z.array(z.object({name:short,steps:z.array(z.object({componentId:z.string(),label:short,fileIds:z.array(z.string()).min(1)})).min(1)})),limitations:z.preprocess(value=>typeof value==='string'?[value]:value??[],z.array(z.string()))});
export const eventSchema=z.object({type:z.enum(['phase','route_selected','route_failed','reset','completed','failed','cancelled']),requestId:z.string().uuid(),attemptId:z.string().uuid().optional(),message:z.string().max(500).optional(),data:z.unknown().optional()}).strict();

export function cappedString(value,max){return String(value??'').replace(/[\x00-\x1f\x7f-\x9f]/g,'').slice(0,max);}
