import {readFileSync,writeFileSync,mkdirSync,renameSync,unlinkSync,existsSync,chmodSync} from 'node:fs';
import {randomBytes,createCipheriv,createDecipheriv} from 'node:crypto';
import {homedir} from 'node:os';
import path from 'node:path';
export const credentialProviders=[['Gemini','GEMINI_API_KEY'],['OpenRouter','OPENROUTER_API_KEY'],['NVIDIA','NVIDIA_API_KEY'],['Ollama Cloud','OLLAMA_API_KEY'],['Compatible API','MEDUSAE_COMPATIBLE_API_KEY']];
export function credentialPaths(){const directory=path.resolve(process.env.MEDUSAE_CREDENTIALS_DIR||path.join(process.env.XDG_CONFIG_HOME||path.join(homedir(),'.config'),'medusae'));return {directory,file:path.join(directory,'credentials.enc'),unlock:path.join(directory,'credentials.key')};}
function readVault(){const p=credentialPaths();if(!existsSync(p.file))return {};try{const data=JSON.parse(readFileSync(p.file,'utf8'));if(data.version!==1)throw new Error();const decipher=createDecipheriv('aes-256-gcm',readFileSync(p.unlock),Buffer.from(data.iv,'base64'));decipher.setAuthTag(Buffer.from(data.tag,'base64'));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(data.data,'base64')),decipher.final()]).toString('utf8'));}catch{throw new Error('Cannot unlock the saved API keys. Restore the credential files or delete the store in Settings.');}}
function writeVault(keys){const p=credentialPaths();mkdirSync(p.directory,{recursive:true,mode:0o700});chmodSync(p.directory,0o700);if(!existsSync(p.unlock))writeFileSync(p.unlock,randomBytes(32),{mode:0o600,flag:'wx'});chmodSync(p.unlock,0o600);const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',readFileSync(p.unlock),iv),data=Buffer.concat([cipher.update(JSON.stringify(keys),'utf8'),cipher.final()]);const temp=p.file+'.'+randomBytes(8).toString('hex')+'.tmp';try{writeFileSync(temp,JSON.stringify({version:1,iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),data:data.toString('base64')}),{mode:0o600,flag:'wx'});renameSync(temp,p.file);}finally{if(existsSync(temp))unlinkSync(temp);}}
function validateName(name){if(!credentialProviders.some(([,key])=>key===name))throw new Error('Unknown credential provider.');}
export function getCredential(name){if(process.env[name])return process.env[name];try{return readVault()[name]||'';}catch{return '';}}
export function credentialStatus(){let keys={},error='';try{keys=readVault();}catch(e){error=e.message;}return {error,paths:credentialPaths(),providers:credentialProviders.map(([label,name])=>({label,name,saved:Boolean(keys[name]),environment:Boolean(process.env[name])}))};}
export function saveCredential(name,value){validateName(name);const key=String(value).trim();if(!key||/[\r\n\x00]/.test(key))throw new Error('Enter a nonempty API key on one line.');const keys=readVault();keys[name]=key;writeVault(keys);}
export function deleteCredential(name){validateName(name);const keys=readVault();delete keys[name];if(Object.keys(keys).length)writeVault(keys);else deleteCredentials();}
export function deleteCredentials(){const p=credentialPaths();for(const file of [p.file,p.unlock]){try{unlinkSync(file);}catch(error){if(error.code!=='ENOENT')throw error;}}}
